export const FORM_DETAIL_REQUEST = 'FORM_DETAIL_REQUEST';
export const FORM_DETAIL_SUCESS = 'FORM_DETAIL_SUCESS';
export const FORM_DETAIL_FAIL = 'FORM_DETAIL_FAIL';


export const FORM_DETAIL_ID_REQUEST = 'FORM_DETAIL_ID_REQUEST';
export const FORM_DETAIL_ID_SUCESS = 'FORM_DETAIL_ID_SUCESS';
export const FORM_DETAIL_ID_FAIL = 'FORM_DETAIL_ID_FAIL';